import type { Abi } from "viem";
export declare const GameHubAbi: Abi;
export declare const VRFHubAbi: Abi;
export declare const PoolRegistryAbi: Abi;
export declare const SettlementRouterAbi: Abi;
export declare const SportsRiskEngineAbi: Abi;
export declare const SportsHubAbi: Abi;
export declare const ReferralRegistryAbi: Abi;
export declare const DefaultReferralEngineAbi: Abi;
export declare const ChainlinkV2PlusWrapperAdapterAbi: Abi;
export declare const DiceModuleAbi: Abi;
export declare const CoinTossModuleAbi: Abi;
export declare const RouletteModuleAbi: Abi;
export declare const KenoModuleAbi: Abi;
export declare const PlinkoModuleAbi: Abi;
export declare const SicBoModuleAbi: Abi;
export declare const SlotsModuleAbi: Abi;
export declare const BaccaratModuleAbi: Abi;
export declare const BankAbi: Abi;
export declare const IGameModuleAbi: Abi;
export declare function getContractAbis(): {
  readonly GameHubAbi: Abi;
  readonly VRFHubAbi: Abi;
  readonly PoolRegistryAbi: Abi;
  readonly SettlementRouterAbi: Abi;
  readonly SportsRiskEngineAbi: Abi;
  readonly SportsHubAbi: Abi;
  readonly ReferralRegistryAbi: Abi;
  readonly DefaultReferralEngineAbi: Abi;
  readonly ChainlinkV2PlusWrapperAdapterAbi: Abi;
  readonly DiceModuleAbi: Abi;
  readonly CoinTossModuleAbi: Abi;
  readonly RouletteModuleAbi: Abi;
  readonly KenoModuleAbi: Abi;
  readonly PlinkoModuleAbi: Abi;
  readonly SicBoModuleAbi: Abi;
  readonly SlotsModuleAbi: Abi;
  readonly BaccaratModuleAbi: Abi;
  readonly BankAbi: Abi;
  readonly IGameModuleAbi: Abi;
};
