// AUTO-GENERATED by pnpm ssot:sync. DO NOT EDIT.

import rchain_84532_json from "./chain-84532.json";

export const embeddedReleases: Record<number, unknown> = {
  [rchain_84532_json.chainId]: rchain_84532_json,
};

export const embeddedChainIds: number[] = Object.keys(embeddedReleases).map((k) => Number(k));
