export const THEME_TOKEN_NAMES = [
  "surface-0",
  "surface-1",
  "surface-2",
  "surface-3",
  "fg",
  "fg-muted",
  "fg-subtle",
  "fg-inverse",
  "border",
  "border-soft",
  "input",
  "ring",
  "brand",
  "brand-hover",
  "brand-active",
  "accent",
  "accent-hover",
  "success",
  "warn",
  "danger",
  "info",
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "radius-sm",
  "radius-md",
  "radius-lg",
  "radius-xl",
  "radius-pill",
  "radius"
] as const;

export type ThemeToken = (typeof THEME_TOKEN_NAMES)[number];
